# This is my own implementation according to v2, which is generated by LLM.


import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.distributed as dist
import einops

from cs336_basics import model, optimizer


def get_named_leaf_modules(root: nn.Module) -> list[tuple[str, nn.Module]]:
  ret = []

  for name, child in root.named_children():
    if child == root:
      continue
    if len(list(child.children())) == 0:
      ret.append((name, child))
    else:
      ret.extend(get_named_leaf_modules(child))

  return ret


def get_leaf_modules(root: nn.Module) -> list[nn.Module]:
  named_leaf_modules = get_named_leaf_modules(root)
  return [m for (_, m) in named_leaf_modules]


def get_leaf_module_types(root: nn.Module) -> set[type[nn.Module]]:
  leaf_modules = get_leaf_modules(root)
  leaf_module_types = [type(m) for m in leaf_modules]
  return set(leaf_module_types)


class FSDPLinearWrapper(nn.Module):
  def __init__(self, module: nn.Module, rank: int, world_size: int):
    super().__init__()
    assert isinstance(module, model.Linear)

    self.rank = rank
    self.world_size = world_size

    # shard the weight.
    chunks = module.weight.data.chunk(chunks=world_size, dim=0)
    local_shard = torch.empty_like(chunks[0])
    if rank == 0:
      dist.scatter(tensor=local_shard, scatter_list=list(chunks), src=0)
    else:
      dist.scatter(tensor=local_shard, scatter_list=None, src=0)
    self.weight = nn.Parameter(local_shard)

  def forward(self, x: torch.Tensor) -> torch.Tensor:
    chunks = [torch.empty_like(self.weight) for _ in range(self.world_size)]
    dist.all_gather(tensor_list=chunks, tensor=self.weight)
    self.weight.data = torch.concat(chunks, dim=0)
    return einops.einsum(x, self.weight, "... d_in, d_out d_in -> ... d_out")


class FSDPEmbeddingWrapper(nn.Module):
  def __init__(self, module: nn.Module, rank: int, world_size: int):
    super().__init__()
    assert isinstance(module, model.Embedding)
    self.rank = rank
    self.world_size = world_size

    # shard the weight.
    chunks = module.weight.data.chunk(chunks=world_size, dim=0)
    local_shard = torch.empty_like(chunks[0])
    if rank == 0:
      dist.scatter(tensor=local_shard, scatter_list=list(chunks), src=0)
    else:
      dist.scatter(tensor=local_shard, scatter_list=None, src=0)
    self.weight = nn.Parameter(local_shard)

  def forward(self, x: torch.Tensor) -> torch.Tensor:
    chunks = [torch.empty_like(self.weight) for _ in range(self.world_size)]
    dist.all_gather(tensor_list=chunks, tensor=self.weight)
    self.weight.data = torch.concat(chunks, dim=0)
    return self.weight[x, :]


class FSDP(nn.Module):
  def __init__(self, module: nn.Module):
    super().__init__()
    self.module = module

    self.rank = dist.get_rank()
    self.world_size = dist.get_world_size()

    leaf_module_types = get_leaf_module_types(self.module)
    if self.rank == 0:
      print(f"Before FSDP: Leaf module types: {leaf_module_types}")

    self._apply_fsdp(self.module)

    leaf_module_types = get_leaf_module_types(self.module)
    if self.rank == 0:
      print(f"After FSDP: Leaf module types: {leaf_module_types}")

  def _apply_fsdp(self, root: nn.Module) -> nn.Module:
    for name, module in root.named_children():
      if module == root:
        continue
      if isinstance(module, model.Linear):
        # print("Wrapping Linear")
        setattr(
          root,
          name,
          FSDPLinearWrapper(module, world_size=self.world_size, rank=self.rank),
        )
      elif isinstance(module, model.Embedding):
        # print("Wrapping embedding")
        setattr(
          root,
          name,
          FSDPEmbeddingWrapper(
            module, world_size=self.world_size, rank=self.rank
          ),
        )
      elif len(list(module.children())) > 0:
        self._apply_fsdp(module)
    return root

  def forward(self, x: torch.Tensor) -> torch.Tensor:
    return self.module(x)

  def finish_gradient_synchronization(self) -> None:
    pass
