# This is my own implementation according to v2, which is generated by LLM.


import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.distributed as dist
import einops
import jaxtyping

from cs336_basics import model, optimizer

from cs336_systems.nn_module_util import get_leaf_modules, get_leaf_module_types


class FSDPLinearFunction(torch.autograd.Function):
  @staticmethod
  def forward(ctx, wrapper, input_tensor, weight):
    """
    Args:
      ctx: Context object to save information for backward pass.
      input_tensor: (..., D_in).
      weight: (D_out, D_in).
    """
    ctx.save_for_backward(input_tensor, weight)
    ctx.world_size = wrapper.world_size

    chunks = [torch.empty_like(weight) for _ in range(wrapper.world_size)]
    dist.all_gather(tensor_list=chunks, tensor=weight)
    full_weight = torch.concat(chunks, dim=0)
    y = einops.einsum(
      input_tensor, full_weight, "... d_in, d_out d_in -> ... d_out"
    )

    return y

  @staticmethod
  def backward(ctx, grad_output):
    grad_output = grad_output  # (..., D_out)
    input_tensor = ctx.saved_tensors[0]  # (..., D_in)
    weight = ctx.saved_tensors[1]  # (D_out / world_size, D_in)
    world_size = ctx.world_size

    # Get the full weight.
    chunks = [torch.empty_like(weight) for _ in range(world_size)]
    dist.all_gather(tensor_list=chunks, tensor=weight)
    full_weight = torch.concat(chunks, dim=0)

    grad_input = einops.einsum(
      grad_output, full_weight, "... d_out, d_out d_in -> ... d_in"
    )
    grad_weight = einops.einsum(
      grad_output, input_tensor, "... d_out, ... d_in -> d_out d_in"
    )

    # sync and shard the local weight gradient.
    grad_weight_chunks = list(grad_weight.chunk(chunks=world_size, dim=0))
    grad_weight_local = torch.empty_like(grad_weight_chunks[0])
    dist.reduce_scatter(
      grad_weight_local, grad_weight_chunks, op=dist.ReduceOp.AVG
    )

    return None, grad_input, grad_weight_local


class FSDPLinearWrapper(nn.Module):
  def __init__(self, module: nn.Module, rank: int, world_size: int):
    super().__init__()
    assert isinstance(module, model.Linear)

    self.rank = rank
    self.world_size = world_size

    # shard the weight.
    chunks = module.weight.data.chunk(chunks=world_size, dim=0)
    local_shard = torch.empty_like(chunks[0])
    if rank == 0:
      dist.scatter(tensor=local_shard, scatter_list=list(chunks), src=0)
    else:
      dist.scatter(tensor=local_shard, scatter_list=None, src=0)
    self.weight = nn.Parameter(local_shard)

  def forward(self, x: torch.Tensor) -> torch.Tensor:
    return FSDPLinearFunction.apply(self, x, self.weight)


class FSDPEmbeddingFunction(torch.autograd.Function):
  @staticmethod
  def forward(ctx, wrapper, input_tensor, weight):
    """
    Args:
      ctx: Context object to save information for backward pass.
      input_tensor: (...,) - indices into the embedding table.
      weight: (vocab_size, embedding_dim).
    """
    ctx.save_for_backward(input_tensor, weight)
    ctx.world_size = wrapper.world_size

    # Sync and assemble the full weight.
    chunks = [torch.empty_like(weight) for _ in range(wrapper.world_size)]
    dist.all_gather(tensor_list=chunks, tensor=weight)
    full_weight = torch.concat(chunks, dim=0)

    y = full_weight[input_tensor, :]  # (..., embedding_dim)
    return y

  @staticmethod
  def backward(ctx, grad_output):
    input_tensor = ctx.saved_tensors[0]  # (...,)
    weight = ctx.saved_tensors[1]  # (vocab_size / world_size, embedding_dim)
    world_size = ctx.world_size

    num_classes = weight.shape[0] * world_size

    input_one_hot = F.one_hot(input_tensor, num_classes=num_classes).to(
      grad_output.dtype
    )  # (..., vocab_size)

    grad_weight = einops.einsum(
      grad_output,
      input_one_hot,
      "... d_int, ... vocab_size -> vocab_size d_int",
    )

    # sync and shard the local weight gradient.
    grad_weight_chunks = list(grad_weight.chunk(chunks=world_size, dim=0))
    grad_weight_local = torch.empty_like(grad_weight_chunks[0])
    dist.reduce_scatter(
      grad_weight_local, grad_weight_chunks, op=dist.ReduceOp.AVG
    )
    return None, None, grad_weight_local


class FSDPEmbeddingWrapper(nn.Module):
  def __init__(self, module: nn.Module, rank: int, world_size: int):
    super().__init__()
    assert isinstance(module, model.Embedding)
    self.rank = rank
    self.world_size = world_size

    # shard the weight.
    chunks = module.weight.data.chunk(chunks=world_size, dim=0)
    local_shard = torch.empty_like(chunks[0])
    if rank == 0:
      dist.scatter(tensor=local_shard, scatter_list=list(chunks), src=0)
    else:
      dist.scatter(tensor=local_shard, scatter_list=None, src=0)
    self.weight = nn.Parameter(local_shard)

  def forward(self, x: torch.Tensor) -> torch.Tensor:
    return FSDPEmbeddingFunction.apply(self, x, self.weight)


class FSDP(nn.Module):
  def __init__(
    self, module: nn.Module, compute_dtype: torch.dtype | None = None
  ):
    super().__init__()
    self.module = module

    self.rank = dist.get_rank()
    self.world_size = dist.get_world_size()

    self.shard_params = set()

    leaf_module_types = get_leaf_module_types(self.module)
    if self.rank == 0:
      print(f"Before FSDP: Leaf module types: {leaf_module_types}")

    self._apply_fsdp(self.module)

    leaf_module_types = get_leaf_module_types(self.module)
    if self.rank == 0:
      print(f"After FSDP: Leaf module types: {leaf_module_types}")

  def _apply_fsdp(self, root: nn.Module) -> nn.Module:
    for name, module in root.named_children():
      if module == root:
        continue
      if isinstance(module, model.Linear):
        # print("Wrapping Linear")
        setattr(
          root,
          name,
          FSDPLinearWrapper(module, world_size=self.world_size, rank=self.rank),
        )
        self.shard_params.add(getattr(root, name).weight)
      elif isinstance(module, model.Embedding):
        # print("Wrapping embedding")
        setattr(
          root,
          name,
          FSDPEmbeddingWrapper(
            module, world_size=self.world_size, rank=self.rank
          ),
        )
        self.shard_params.add(getattr(root, name).weight)
      elif len(list(module.children())) > 0:
        self._apply_fsdp(module)
    return root

  def forward(self, x: torch.Tensor) -> torch.Tensor:
    return self.module(x)

  def finish_gradient_synchronization(self) -> None:
    # Sync the replicated params' gradients.
    for param in self.module.parameters():
      if param not in self.shard_params:
        dist.all_reduce(param.grad, op=dist.ReduceOp.AVG)

  def gather_full_params(self) -> dict[str, torch.Tensor]:
    """All-gather sharded params to reconstruct full parameter tensors.

    Replicated parameters are returned as-is."""
    ret = {}
    for name, param in self.module.named_parameters():
      if param not in self.shard_params:
        ret[name] = param.data
      else:
        chunks = []
        for _ in range(self.world_size):
          chunks.append(torch.empty_like(param.data))
        dist.all_gather(chunks, param.data.detach())
        ret[name] = torch.concat(chunks, dim=0)
    return ret
